import SaintHelenaAscensionAndTristandaCunhaFlag from './SaintHelenaAscensionAndTristandaCunhaFlag.vue'
SaintHelenaAscensionAndTristandaCunhaFlag.install = app => {
  app.component(SaintHelenaAscensionAndTristandaCunhaFlag.name, SaintHelenaAscensionAndTristandaCunhaFlag)
}
export default SaintHelenaAscensionAndTristandaCunhaFlag;