import SouthGeorgiaAndtheSouthSandwichIslandsFlag from './SouthGeorgiaAndtheSouthSandwichIslandsFlag.vue'
SouthGeorgiaAndtheSouthSandwichIslandsFlag.install = app => {
  app.component(SouthGeorgiaAndtheSouthSandwichIslandsFlag.name, SouthGeorgiaAndtheSouthSandwichIslandsFlag)
}
export default SouthGeorgiaAndtheSouthSandwichIslandsFlag;