export const define = {
  __SFC_TEMPLATE_TARGET__: "__SFC_TEMPLATE_TARGET__",
  __EXPORT_NAME__: "__EXPORT_NAME__",
  __INDEX_IMPORTS_TARGET__: "__INDEX_IMPORTS_TARGET__",
  __INDEX_EXPORTS_TARGET__: "__INDEX_EXPORTS_TARGET__",
  __TEST_TARGET__: "__TEST_TARGET__",
  __TEST_IMPORT__: "__TEST_IMPORT__",
  __MANIFEST_TARGET__: "__MANIFEST_TARGET__",
  __H_TEST_TARGET__: "__H_TEST_TARGET__",
  __H_TEST_TEMPLATE_TARGET__: "__H_TEST_TEMPLATE_TARGET__",
};
