import * as Components from "../index.js";

export const ComponentCodeName = {
  af: { enName: "Afghanistan", component: Components.AfghanistanFlag },
  ax: { enName: "AlandIslands", component: Components.AlandIslandsFlag },
  al: { enName: "Albania", component: Components.AlbaniaFlag },
  dz: { enName: "Algeria", component: Components.AlgeriaFlag },
  as: { enName: "AmericanSamoa", component: Components.AmericanSamoaFlag },
  ad: { enName: "Andorra", component: Components.AndorraFlag },
  ao: { enName: "Angola", component: Components.AngolaFlag },
  ai: { enName: "Anguilla", component: Components.AnguillaFlag },
  aq: { enName: "Antarctica", component: Components.AntarcticaFlag },
  ag: {
    enName: "AntiguaAndBarbuda",
    component: Components.AntiguaAndBarbudaFlag,
  },
  ar: { enName: "Argentina", component: Components.ArgentinaFlag },
  am: { enName: "Armenia", component: Components.ArmeniaFlag },
  aw: { enName: "Aruba", component: Components.ArubaFlag },
  ac: { enName: "AscensionIsland", component: Components.AscensionIslandFlag },
  au: { enName: "Australia", component: Components.AustraliaFlag },
  at: { enName: "Austria", component: Components.AustriaFlag },
  az: { enName: "Azerbaijan", component: Components.AzerbaijanFlag },
  bs: { enName: "Bahamas", component: Components.BahamasFlag },
  bh: { enName: "Bahrain", component: Components.BahrainFlag },
  bd: { enName: "Bangladesh", component: Components.BangladeshFlag },
  bb: { enName: "Barbados", component: Components.BarbadosFlag },
  by: { enName: "Belarus", component: Components.BelarusFlag },
  be: { enName: "Belgium", component: Components.BelgiumFlag },
  bz: { enName: "Belize", component: Components.BelizeFlag },
  bj: { enName: "Benin", component: Components.BeninFlag },
  bm: { enName: "Bermuda", component: Components.BermudaFlag },
  bt: { enName: "Bhutan", component: Components.BhutanFlag },
  bo: { enName: "Bolivia", component: Components.BoliviaFlag },
  bq: {
    enName: "BonaireSintEustatiusAndSaba",
    component: Components.BonaireSintEustatiusAndSabaFlag,
  },
  ba: {
    enName: "BosniaAndHerzegovina",
    component: Components.BosniaAndHerzegovinaFlag,
  },
  bw: { enName: "Botswana", component: Components.BotswanaFlag },
  bv: { enName: "BouvetIsland", component: Components.BouvetIslandFlag },
  br: { enName: "Brazil", component: Components.BrazilFlag },
  io: {
    enName: "BritishIndianOceanTerritory",
    component: Components.BritishIndianOceanTerritoryFlag,
  },
  bn: {
    enName: "BruneiDarussalam",
    component: Components.BruneiDarussalamFlag,
  },
  bg: { enName: "Bulgaria", component: Components.BulgariaFlag },
  bf: { enName: "BurkinaFaso", component: Components.BurkinaFasoFlag },
  bi: { enName: "Burundi", component: Components.BurundiFlag },
  cv: { enName: "CaboVerde", component: Components.CaboVerdeFlag },
  kh: { enName: "Cambodia", component: Components.CambodiaFlag },
  cm: { enName: "Cameroon", component: Components.CameroonFlag },
  ca: { enName: "Canada", component: Components.CanadaFlag },
  ic: { enName: "CanaryIslands", component: Components.CanaryIslandsFlag },
  "es-ct": { enName: "Catalonia", component: Components.CataloniaFlag },
  ky: { enName: "CaymanIslands", component: Components.CaymanIslandsFlag },
  cf: {
    enName: "CentralAfricanRepublic",
    component: Components.CentralAfricanRepublicFlag,
  },
  cefta: {
    enName: "CentralEuropeanFreeTradeAgreement",
    component: Components.CentralEuropeanFreeTradeAgreementFlag,
  },
  ea: { enName: "CeutaMelilla", component: Components.CeutaMelillaFlag },
  td: { enName: "Chad", component: Components.ChadFlag },
  cl: { enName: "Chile", component: Components.ChileFlag },
  cn: { enName: "China", component: Components.ChinaFlag },
  cx: { enName: "ChristmasIsland", component: Components.ChristmasIslandFlag },
  cp: {
    enName: "ClippertonIsland",
    component: Components.ClippertonIslandFlag,
  },
  cc: {
    enName: "CocosKeelingIslands",
    component: Components.CocosKeelingIslandsFlag,
  },
  co: { enName: "Colombia", component: Components.ColombiaFlag },
  km: { enName: "Comoros", component: Components.ComorosFlag },
  ck: { enName: "CookIslands", component: Components.CookIslandsFlag },
  cr: { enName: "CostaRica", component: Components.CostaRicaFlag },
  hr: { enName: "Croatia", component: Components.CroatiaFlag },
  cu: { enName: "Cuba", component: Components.CubaFlag },
  cw: { enName: "Curaao", component: Components.CuraaoFlag },
  cy: { enName: "Cyprus", component: Components.CyprusFlag },
  cz: { enName: "CzechRepublic", component: Components.CzechRepublicFlag },
  ci: { enName: "CtedIvoire", component: Components.CtedIvoireFlag },
  cd: {
    enName: "DemocraticRepublicoftheCongo",
    component: Components.DemocraticRepublicoftheCongoFlag,
  },
  dk: { enName: "Denmark", component: Components.DenmarkFlag },
  dg: { enName: "DiegoGarcia", component: Components.DiegoGarciaFlag },
  dj: { enName: "Djibouti", component: Components.DjiboutiFlag },
  dm: { enName: "Dominica", component: Components.DominicaFlag },
  do: {
    enName: "DominicanRepublic",
    component: Components.DominicanRepublicFlag,
  },
  ec: { enName: "Ecuador", component: Components.EcuadorFlag },
  eg: { enName: "Egypt", component: Components.EgyptFlag },
  sv: { enName: "ElSalvador", component: Components.ElSalvadorFlag },
  "gb-eng": { enName: "England", component: Components.EnglandFlag },
  gq: {
    enName: "EquatorialGuinea",
    component: Components.EquatorialGuineaFlag,
  },
  er: { enName: "Eritrea", component: Components.EritreaFlag },
  ee: { enName: "Estonia", component: Components.EstoniaFlag },
  sz: { enName: "Eswatini", component: Components.EswatiniFlag },
  et: { enName: "Ethiopia", component: Components.EthiopiaFlag },
  eu: { enName: "Europe", component: Components.EuropeFlag },
  fk: { enName: "FalklandIslands", component: Components.FalklandIslandsFlag },
  fo: { enName: "FaroeIslands", component: Components.FaroeIslandsFlag },
  fm: {
    enName: "FederatedStatesofMicronesia",
    component: Components.FederatedStatesofMicronesiaFlag,
  },
  fj: { enName: "Fiji", component: Components.FijiFlag },
  fi: { enName: "Finland", component: Components.FinlandFlag },
  fr: { enName: "France", component: Components.FranceFlag },
  gf: { enName: "FrenchGuiana", component: Components.FrenchGuianaFlag },
  pf: { enName: "FrenchPolynesia", component: Components.FrenchPolynesiaFlag },
  tf: {
    enName: "FrenchSouthernTerritories",
    component: Components.FrenchSouthernTerritoriesFlag,
  },
  ga: { enName: "Gabon", component: Components.GabonFlag },
  "es-ga": { enName: "Galicia", component: Components.GaliciaFlag },
  gm: { enName: "Gambia", component: Components.GambiaFlag },
  ge: { enName: "Georgia", component: Components.GeorgiaFlag },
  de: { enName: "Germany", component: Components.GermanyFlag },
  gh: { enName: "Ghana", component: Components.GhanaFlag },
  gi: { enName: "Gibraltar", component: Components.GibraltarFlag },
  gr: { enName: "Greece", component: Components.GreeceFlag },
  gl: { enName: "Greenland", component: Components.GreenlandFlag },
  gd: { enName: "Grenada", component: Components.GrenadaFlag },
  gp: { enName: "Guadeloupe", component: Components.GuadeloupeFlag },
  gu: { enName: "Guam", component: Components.GuamFlag },
  gt: { enName: "Guatemala", component: Components.GuatemalaFlag },
  gg: { enName: "Guernsey", component: Components.GuernseyFlag },
  gn: { enName: "Guinea", component: Components.GuineaFlag },
  gw: { enName: "GuineaBissau", component: Components.GuineaBissauFlag },
  gy: { enName: "Guyana", component: Components.GuyanaFlag },
  ht: { enName: "Haiti", component: Components.HaitiFlag },
  hm: {
    enName: "HeardIslandAndMcDonaldIslands",
    component: Components.HeardIslandAndMcDonaldIslandsFlag,
  },
  va: { enName: "HolySee", component: Components.HolySeeFlag },
  hn: { enName: "Honduras", component: Components.HondurasFlag },
  hk: { enName: "ChinaHongKong", component: Components.ChinaHongKongFlag },
  hu: { enName: "Hungary", component: Components.HungaryFlag },
  is: { enName: "Iceland", component: Components.IcelandFlag },
  in: { enName: "India", component: Components.IndiaFlag },
  id: { enName: "Indonesia", component: Components.IndonesiaFlag },
  ir: { enName: "Iran", component: Components.IranFlag },
  iq: { enName: "Iraq", component: Components.IraqFlag },
  ie: { enName: "Ireland", component: Components.IrelandFlag },
  im: { enName: "IsleofMan", component: Components.IsleofManFlag },
  il: { enName: "Israel", component: Components.IsraelFlag },
  it: { enName: "Italy", component: Components.ItalyFlag },
  jm: { enName: "Jamaica", component: Components.JamaicaFlag },
  jp: { enName: "Japan", component: Components.JapanFlag },
  je: { enName: "Jersey", component: Components.JerseyFlag },
  jo: { enName: "Jordan", component: Components.JordanFlag },
  kz: { enName: "Kazakhstan", component: Components.KazakhstanFlag },
  ke: { enName: "Kenya", component: Components.KenyaFlag },
  ki: { enName: "Kiribati", component: Components.KiribatiFlag },
  xk: { enName: "Kosovo", component: Components.KosovoFlag },
  kw: { enName: "Kuwait", component: Components.KuwaitFlag },
  kg: { enName: "Kyrgyzstan", component: Components.KyrgyzstanFlag },
  la: { enName: "Laos", component: Components.LaosFlag },
  lv: { enName: "Latvia", component: Components.LatviaFlag },
  lb: { enName: "Lebanon", component: Components.LebanonFlag },
  ls: { enName: "Lesotho", component: Components.LesothoFlag },
  lr: { enName: "Liberia", component: Components.LiberiaFlag },
  ly: { enName: "Libya", component: Components.LibyaFlag },
  li: { enName: "Liechtenstein", component: Components.LiechtensteinFlag },
  lt: { enName: "Lithuania", component: Components.LithuaniaFlag },
  lu: { enName: "Luxembourg", component: Components.LuxembourgFlag },
  mo: { enName: "ChinaMacau", component: Components.ChinaMacauFlag },
  mg: { enName: "Madagascar", component: Components.MadagascarFlag },
  mw: { enName: "Malawi", component: Components.MalawiFlag },
  my: { enName: "Malaysia", component: Components.MalaysiaFlag },
  mv: { enName: "Maldives", component: Components.MaldivesFlag },
  ml: { enName: "Mali", component: Components.MaliFlag },
  mt: { enName: "Malta", component: Components.MaltaFlag },
  mh: { enName: "MarshallIslands", component: Components.MarshallIslandsFlag },
  mq: { enName: "Martinique", component: Components.MartiniqueFlag },
  mr: { enName: "Mauritania", component: Components.MauritaniaFlag },
  mu: { enName: "Mauritius", component: Components.MauritiusFlag },
  yt: { enName: "Mayotte", component: Components.MayotteFlag },
  mx: { enName: "Mexico", component: Components.MexicoFlag },
  md: { enName: "Moldova", component: Components.MoldovaFlag },
  mc: { enName: "Monaco", component: Components.MonacoFlag },
  mn: { enName: "Mongolia", component: Components.MongoliaFlag },
  me: { enName: "Montenegro", component: Components.MontenegroFlag },
  ms: { enName: "Montserrat", component: Components.MontserratFlag },
  ma: { enName: "Morocco", component: Components.MoroccoFlag },
  mz: { enName: "Mozambique", component: Components.MozambiqueFlag },
  mm: { enName: "Myanmar", component: Components.MyanmarFlag },
  na: { enName: "Namibia", component: Components.NamibiaFlag },
  nr: { enName: "Nauru", component: Components.NauruFlag },
  np: { enName: "Nepal", component: Components.NepalFlag },
  nl: { enName: "Netherlands", component: Components.NetherlandsFlag },
  nc: { enName: "NewCaledonia", component: Components.NewCaledoniaFlag },
  nz: { enName: "NewZealand", component: Components.NewZealandFlag },
  ni: { enName: "Nicaragua", component: Components.NicaraguaFlag },
  ne: { enName: "Niger", component: Components.NigerFlag },
  ng: { enName: "Nigeria", component: Components.NigeriaFlag },
  nu: { enName: "Niue", component: Components.NiueFlag },
  nf: { enName: "NorfolkIsland", component: Components.NorfolkIslandFlag },
  kp: { enName: "NorthKorea", component: Components.NorthKoreaFlag },
  mk: { enName: "NorthMacedonia", component: Components.NorthMacedoniaFlag },
  "gb-nir": {
    enName: "NorthernIreland",
    component: Components.NorthernIrelandFlag,
  },
  mp: {
    enName: "NorthernMarianaIslands",
    component: Components.NorthernMarianaIslandsFlag,
  },
  no: { enName: "Norway", component: Components.NorwayFlag },
  om: { enName: "Oman", component: Components.OmanFlag },
  pk: { enName: "Pakistan", component: Components.PakistanFlag },
  pw: { enName: "Palau", component: Components.PalauFlag },
  pa: { enName: "Panama", component: Components.PanamaFlag },
  pg: { enName: "PapuaNewGuinea", component: Components.PapuaNewGuineaFlag },
  py: { enName: "Paraguay", component: Components.ParaguayFlag },
  pe: { enName: "Peru", component: Components.PeruFlag },
  ph: { enName: "Philippines", component: Components.PhilippinesFlag },
  pn: { enName: "Pitcairn", component: Components.PitcairnFlag },
  pl: { enName: "Poland", component: Components.PolandFlag },
  pt: { enName: "Portugal", component: Components.PortugalFlag },
  pr: { enName: "PuertoRico", component: Components.PuertoRicoFlag },
  qa: { enName: "Qatar", component: Components.QatarFlag },
  cg: {
    enName: "RepublicoftheCongo",
    component: Components.RepublicoftheCongoFlag,
  },
  ro: { enName: "Romania", component: Components.RomaniaFlag },
  ru: { enName: "Russia", component: Components.RussiaFlag },
  rw: { enName: "Rwanda", component: Components.RwandaFlag },
  re: { enName: "Runion", component: Components.RunionFlag },
  bl: { enName: "SaintBarthlemy", component: Components.SaintBarthlemyFlag },
  sh: {
    enName: "SaintHelenaAscensionAndTristandaCunha",
    component: Components.SaintHelenaAscensionAndTristandaCunhaFlag,
  },
  kn: {
    enName: "SaintKittsAndNevis",
    component: Components.SaintKittsAndNevisFlag,
  },
  lc: { enName: "SaintLucia", component: Components.SaintLuciaFlag },
  mf: { enName: "SaintMartin", component: Components.SaintMartinFlag },
  pm: {
    enName: "SaintPierreAndMiquelon",
    component: Components.SaintPierreAndMiquelonFlag,
  },
  vc: {
    enName: "SaintVincentAndtheGrenadines",
    component: Components.SaintVincentAndtheGrenadinesFlag,
  },
  ws: { enName: "Samoa", component: Components.SamoaFlag },
  sm: { enName: "SanMarino", component: Components.SanMarinoFlag },
  st: {
    enName: "SaoTomeAndPrincipe",
    component: Components.SaoTomeAndPrincipeFlag,
  },
  sa: { enName: "SaudiArabia", component: Components.SaudiArabiaFlag },
  "gb-sct": { enName: "Scotland", component: Components.ScotlandFlag },
  sn: { enName: "Senegal", component: Components.SenegalFlag },
  rs: { enName: "Serbia", component: Components.SerbiaFlag },
  sc: { enName: "Seychelles", component: Components.SeychellesFlag },
  sl: { enName: "SierraLeone", component: Components.SierraLeoneFlag },
  sg: { enName: "Singapore", component: Components.SingaporeFlag },
  sx: { enName: "SintMaarten", component: Components.SintMaartenFlag },
  sk: { enName: "Slovakia", component: Components.SlovakiaFlag },
  si: { enName: "Slovenia", component: Components.SloveniaFlag },
  sb: { enName: "SolomonIslands", component: Components.SolomonIslandsFlag },
  so: { enName: "Somalia", component: Components.SomaliaFlag },
  za: { enName: "SouthAfrica", component: Components.SouthAfricaFlag },
  gs: {
    enName: "SouthGeorgiaAndtheSouthSandwichIslands",
    component: Components.SouthGeorgiaAndtheSouthSandwichIslandsFlag,
  },
  kr: { enName: "SouthKorea", component: Components.SouthKoreaFlag },
  ss: { enName: "SouthSudan", component: Components.SouthSudanFlag },
  es: { enName: "Spain", component: Components.SpainFlag },
  lk: { enName: "SriLanka", component: Components.SriLankaFlag },
  ps: {
    enName: "StateofPalestine",
    component: Components.StateofPalestineFlag,
  },
  sd: { enName: "Sudan", component: Components.SudanFlag },
  sr: { enName: "Suriname", component: Components.SurinameFlag },
  sj: {
    enName: "SvalbardAndJanMayen",
    component: Components.SvalbardAndJanMayenFlag,
  },
  se: { enName: "Sweden", component: Components.SwedenFlag },
  ch: { enName: "Switzerland", component: Components.SwitzerlandFlag },
  sy: { enName: "Syria", component: Components.SyriaFlag },
  tw: { enName: "ChinaTaiwan", component: Components.ChinaTaiwanFlag },
  tj: { enName: "Tajikistan", component: Components.TajikistanFlag },
  tz: { enName: "Tanzania", component: Components.TanzaniaFlag },
  th: { enName: "Thailand", component: Components.ThailandFlag },
  tl: { enName: "TimorLeste", component: Components.TimorLesteFlag },
  tg: { enName: "Togo", component: Components.TogoFlag },
  tk: { enName: "Tokelau", component: Components.TokelauFlag },
  to: { enName: "Tonga", component: Components.TongaFlag },
  tt: {
    enName: "TrinidadAndTobago",
    component: Components.TrinidadAndTobagoFlag,
  },
  ta: { enName: "TristandaCunha", component: Components.TristandaCunhaFlag },
  tn: { enName: "Tunisia", component: Components.TunisiaFlag },
  tr: { enName: "Turkey", component: Components.TurkeyFlag },
  tm: { enName: "Turkmenistan", component: Components.TurkmenistanFlag },
  tc: {
    enName: "TurksAndCaicosIslands",
    component: Components.TurksAndCaicosIslandsFlag,
  },
  tv: { enName: "Tuvalu", component: Components.TuvaluFlag },
  ug: { enName: "Uganda", component: Components.UgandaFlag },
  ua: { enName: "Ukraine", component: Components.UkraineFlag },
  ae: {
    enName: "UnitedArabEmirates",
    component: Components.UnitedArabEmiratesFlag,
  },
  gb: { enName: "UnitedKingdom", component: Components.UnitedKingdomFlag },
  un: { enName: "UnitedNations", component: Components.UnitedNationsFlag },
  um: {
    enName: "UnitedStatesMinorOutlyingIslands",
    component: Components.UnitedStatesMinorOutlyingIslandsFlag,
  },
  us: {
    enName: "UnitedStatesofAmerica",
    component: Components.UnitedStatesofAmericaFlag,
  },
  xx: { enName: "Unknown", component: Components.UnknownFlag },
  uy: { enName: "Uruguay", component: Components.UruguayFlag },
  uz: { enName: "Uzbekistan", component: Components.UzbekistanFlag },
  vu: { enName: "Vanuatu", component: Components.VanuatuFlag },
  ve: { enName: "Venezuela", component: Components.VenezuelaFlag },
  vn: { enName: "Vietnam", component: Components.VietnamFlag },
  vg: {
    enName: "VirginIslandsBritish",
    component: Components.VirginIslandsBritishFlag,
  },
  vi: { enName: "VirginIslandsUS", component: Components.VirginIslandsUSFlag },
  "gb-wls": { enName: "Wales", component: Components.WalesFlag },
  wf: { enName: "WallisAndFutuna", component: Components.WallisAndFutunaFlag },
  eh: { enName: "WesternSahara", component: Components.WesternSaharaFlag },
  ye: { enName: "Yemen", component: Components.YemenFlag },
  zm: { enName: "Zambia", component: Components.ZambiaFlag },
  zw: { enName: "Zimbabwe", component: Components.ZimbabweFlag },
};
