export const CountryCodeName = {
  af: { enName: "Afghanistan", asset: "af.svg" },
  ax: { enName: "Aland Islands", asset: "ax.svg" },
  al: { enName: "Albania", asset: "al.svg" },
  dz: { enName: "Algeria", asset: "dz.svg" },
  as: { enName: "American Samoa", asset: "as.svg" },
  ad: { enName: "Andorra", asset: "ad.svg" },
  ao: { enName: "Angola", asset: "ao.svg" },
  ai: { enName: "Anguilla", asset: "ai.svg" },
  aq: { enName: "Antarctica", asset: "aq.svg" },
  ag: { enName: "Antigua And Barbuda", asset: "ag.svg" },
  ar: { enName: "Argentina", asset: "ar.svg" },
  am: { enName: "Armenia", asset: "am.svg" },
  aw: { enName: "Aruba", asset: "aw.svg" },
  ac: { enName: "Ascension Island", asset: "ac.svg" },
  au: { enName: "Australia", asset: "au.svg" },
  at: { enName: "Austria", asset: "at.svg" },
  az: { enName: "Azerbaijan", asset: "az.svg" },
  bs: { enName: "Bahamas", asset: "bs.svg" },
  bh: { enName: "Bahrain", asset: "bh.svg" },
  bd: { enName: "Bangladesh", asset: "bd.svg" },
  bb: { enName: "Barbados", asset: "bb.svg" },
  by: { enName: "Belarus", asset: "by.svg" },
  be: { enName: "Belgium", asset: "be.svg" },
  bz: { enName: "Belize", asset: "bz.svg" },
  bj: { enName: "Benin", asset: "bj.svg" },
  bm: { enName: "Bermuda", asset: "bm.svg" },
  bt: { enName: "Bhutan", asset: "bt.svg" },
  bo: { enName: "Bolivia", asset: "bo.svg" },
  bq: { enName: "Bonaire, Sint Eustatius And Saba", asset: "bq.svg" },
  ba: { enName: "Bosnia And Herzegovina", asset: "ba.svg" },
  bw: { enName: "Botswana", asset: "bw.svg" },
  bv: { enName: "Bouvet Island", asset: "bv.svg" },
  br: { enName: "Brazil", asset: "br.svg" },
  io: { enName: "British Indian Ocean Territory", asset: "io.svg" },
  bn: { enName: "Brunei Darussalam", asset: "bn.svg" },
  bg: { enName: "Bulgaria", asset: "bg.svg" },
  bf: { enName: "Burkina Faso", asset: "bf.svg" },
  bi: { enName: "Burundi", asset: "bi.svg" },
  cv: { enName: "Cabo Verde", asset: "cv.svg" },
  kh: { enName: "Cambodia", asset: "kh.svg" },
  cm: { enName: "Cameroon", asset: "cm.svg" },
  ca: { enName: "Canada", asset: "ca.svg" },
  ic: { enName: "Canary Islands", asset: "ic.svg" },
  "es-ct": { enName: "Catalonia", asset: "es-ct.svg" },
  ky: { enName: "Cayman Islands", asset: "ky.svg" },
  cf: { enName: "Central African Republic", asset: "cf.svg" },
  cefta: {
    enName: "Central European Free Trade Agreement",
    asset: "cefta.svg",
  },
  ea: { enName: "Ceuta & Melilla", asset: "ea.svg" },
  td: { enName: "Chad", asset: "td.svg" },
  cl: { enName: "Chile", asset: "cl.svg" },
  cn: { enName: "China", asset: "cn.svg" },
  cx: { enName: "Christmas Island", asset: "cx.svg" },
  cp: { enName: "Clipperton Island", asset: "cp.svg" },
  cc: { enName: "Cocos (Keeling) Islands", asset: "cc.svg" },
  co: { enName: "Colombia", asset: "co.svg" },
  km: { enName: "Comoros", asset: "km.svg" },
  ck: { enName: "Cook Islands", asset: "ck.svg" },
  cr: { enName: "Costa Rica", asset: "cr.svg" },
  hr: { enName: "Croatia", asset: "hr.svg" },
  cu: { enName: "Cuba", asset: "cu.svg" },
  cw: { enName: "Curaçao", asset: "cw.svg" },
  cy: { enName: "Cyprus", asset: "cy.svg" },
  cz: { enName: "Czech Republic", asset: "cz.svg" },
  ci: { enName: "Côte d'Ivoire", asset: "ci.svg" },
  cd: { enName: "Democratic Republic of the Congo", asset: "cd.svg" },
  dk: { enName: "Denmark", asset: "dk.svg" },
  dg: { enName: "Diego Garcia", asset: "dg.svg" },
  dj: { enName: "Djibouti", asset: "dj.svg" },
  dm: { enName: "Dominica", asset: "dm.svg" },
  do: { enName: "Dominican Republic", asset: "do.svg" },
  ec: { enName: "Ecuador", asset: "ec.svg" },
  eg: { enName: "Egypt", asset: "eg.svg" },
  sv: { enName: "El Salvador", asset: "sv.svg" },
  "gb-eng": { enName: "England", asset: "gb-eng.svg" },
  gq: { enName: "Equatorial Guinea", asset: "gq.svg" },
  er: { enName: "Eritrea", asset: "er.svg" },
  ee: { enName: "Estonia", asset: "ee.svg" },
  sz: { enName: "Eswatini", asset: "sz.svg" },
  et: { enName: "Ethiopia", asset: "et.svg" },
  eu: { enName: "Europe", asset: "eu.svg" },
  fk: { enName: "Falkland Islands", asset: "fk.svg" },
  fo: { enName: "Faroe Islands", asset: "fo.svg" },
  fm: { enName: "Federated States of Micronesia", asset: "fm.svg" },
  fj: { enName: "Fiji", asset: "fj.svg" },
  fi: { enName: "Finland", asset: "fi.svg" },
  fr: { enName: "France", asset: "fr.svg" },
  gf: { enName: "French Guiana", asset: "gf.svg" },
  pf: { enName: "French Polynesia", asset: "pf.svg" },
  tf: { enName: "French Southern Territories", asset: "tf.svg" },
  ga: { enName: "Gabon", asset: "ga.svg" },
  "es-ga": { enName: "Galicia", asset: "es-ga.svg" },
  gm: { enName: "Gambia", asset: "gm.svg" },
  ge: { enName: "Georgia", asset: "ge.svg" },
  de: { enName: "Germany", asset: "de.svg" },
  gh: { enName: "Ghana", asset: "gh.svg" },
  gi: { enName: "Gibraltar", asset: "gi.svg" },
  gr: { enName: "Greece", asset: "gr.svg" },
  gl: { enName: "Greenland", asset: "gl.svg" },
  gd: { enName: "Grenada", asset: "gd.svg" },
  gp: { enName: "Guadeloupe", asset: "gp.svg" },
  gu: { enName: "Guam", asset: "gu.svg" },
  gt: { enName: "Guatemala", asset: "gt.svg" },
  gg: { enName: "Guernsey", asset: "gg.svg" },
  gn: { enName: "Guinea", asset: "gn.svg" },
  gw: { enName: "Guinea-Bissau", asset: "gw.svg" },
  gy: { enName: "Guyana", asset: "gy.svg" },
  ht: { enName: "Haiti", asset: "ht.svg" },
  hm: { enName: "Heard Island And McDonald Islands", asset: "hm.svg" },
  va: { enName: "Holy See", asset: "va.svg" },
  hn: { enName: "Honduras", asset: "hn.svg" },
  hk: { enName: "China Hong Kong", asset: "hk.svg" },
  hu: { enName: "Hungary", asset: "hu.svg" },
  is: { enName: "Iceland", asset: "is.svg" },
  in: { enName: "India", asset: "in.svg" },
  id: { enName: "Indonesia", asset: "id.svg" },
  ir: { enName: "Iran", asset: "ir.svg" },
  iq: { enName: "Iraq", asset: "iq.svg" },
  ie: { enName: "Ireland", asset: "ie.svg" },
  im: { enName: "Isle of Man", asset: "im.svg" },
  il: { enName: "Israel", asset: "il.svg" },
  it: { enName: "Italy", asset: "it.svg" },
  jm: { enName: "Jamaica", asset: "jm.svg" },
  jp: { enName: "Japan", asset: "jp.svg" },
  je: { enName: "Jersey", asset: "je.svg" },
  jo: { enName: "Jordan", asset: "jo.svg" },
  kz: { enName: "Kazakhstan", asset: "kz.svg" },
  ke: { enName: "Kenya", asset: "ke.svg" },
  ki: { enName: "Kiribati", asset: "ki.svg" },
  xk: { enName: "Kosovo", asset: "xk.svg" },
  kw: { enName: "Kuwait", asset: "kw.svg" },
  kg: { enName: "Kyrgyzstan", asset: "kg.svg" },
  la: { enName: "Laos", asset: "la.svg" },
  lv: { enName: "Latvia", asset: "lv.svg" },
  lb: { enName: "Lebanon", asset: "lb.svg" },
  ls: { enName: "Lesotho", asset: "ls.svg" },
  lr: { enName: "Liberia", asset: "lr.svg" },
  ly: { enName: "Libya", asset: "ly.svg" },
  li: { enName: "Liechtenstein", asset: "li.svg" },
  lt: { enName: "Lithuania", asset: "lt.svg" },
  lu: { enName: "Luxembourg", asset: "lu.svg" },
  mo: { enName: "China Macau", asset: "mo.svg" },
  mg: { enName: "Madagascar", asset: "mg.svg" },
  mw: { enName: "Malawi", asset: "mw.svg" },
  my: { enName: "Malaysia", asset: "my.svg" },
  mv: { enName: "Maldives", asset: "mv.svg" },
  ml: { enName: "Mali", asset: "ml.svg" },
  mt: { enName: "Malta", asset: "mt.svg" },
  mh: { enName: "Marshall Islands", asset: "mh.svg" },
  mq: { enName: "Martinique", asset: "mq.svg" },
  mr: { enName: "Mauritania", asset: "mr.svg" },
  mu: { enName: "Mauritius", asset: "mu.svg" },
  yt: { enName: "Mayotte", asset: "yt.svg" },
  mx: { enName: "Mexico", asset: "mx.svg" },
  md: { enName: "Moldova", asset: "md.svg" },
  mc: { enName: "Monaco", asset: "mc.svg" },
  mn: { enName: "Mongolia", asset: "mn.svg" },
  me: { enName: "Montenegro", asset: "me.svg" },
  ms: { enName: "Montserrat", asset: "ms.svg" },
  ma: { enName: "Morocco", asset: "ma.svg" },
  mz: { enName: "Mozambique", asset: "mz.svg" },
  mm: { enName: "Myanmar", asset: "mm.svg" },
  na: { enName: "Namibia", asset: "na.svg" },
  nr: { enName: "Nauru", asset: "nr.svg" },
  np: { enName: "Nepal", asset: "np.svg" },
  nl: { enName: "Netherlands", asset: "nl.svg" },
  nc: { enName: "New Caledonia", asset: "nc.svg" },
  nz: { enName: "New Zealand", asset: "nz.svg" },
  ni: { enName: "Nicaragua", asset: "ni.svg" },
  ne: { enName: "Niger", asset: "ne.svg" },
  ng: { enName: "Nigeria", asset: "ng.svg" },
  nu: { enName: "Niue", asset: "nu.svg" },
  nf: { enName: "Norfolk Island", asset: "nf.svg" },
  kp: { enName: "North Korea", asset: "kp.svg" },
  mk: { enName: "North Macedonia", asset: "mk.svg" },
  "gb-nir": { enName: "Northern Ireland", asset: "gb-nir.svg" },
  mp: { enName: "Northern Mariana Islands", asset: "mp.svg" },
  no: { enName: "Norway", asset: "no.svg" },
  om: { enName: "Oman", asset: "om.svg" },
  pk: { enName: "Pakistan", asset: "pk.svg" },
  pw: { enName: "Palau", asset: "pw.svg" },
  pa: { enName: "Panama", asset: "pa.svg" },
  pg: { enName: "Papua New Guinea", asset: "pg.svg" },
  py: { enName: "Paraguay", asset: "py.svg" },
  pe: { enName: "Peru", asset: "pe.svg" },
  ph: { enName: "Philippines", asset: "ph.svg" },
  pn: { enName: "Pitcairn", asset: "pn.svg" },
  pl: { enName: "Poland", asset: "pl.svg" },
  pt: { enName: "Portugal", asset: "pt.svg" },
  pr: { enName: "Puerto Rico", asset: "pr.svg" },
  qa: { enName: "Qatar", asset: "qa.svg" },
  cg: { enName: "Republic of the Congo", asset: "cg.svg" },
  ro: { enName: "Romania", asset: "ro.svg" },
  ru: { enName: "Russia", asset: "ru.svg" },
  rw: { enName: "Rwanda", asset: "rw.svg" },
  re: { enName: "Réunion", asset: "re.svg" },
  bl: { enName: "Saint Barthélemy", asset: "bl.svg" },
  sh: {
    enName: "Saint Helena, Ascension And Tristan da Cunha",
    asset: "sh.svg",
  },
  kn: { enName: "Saint Kitts And Nevis", asset: "kn.svg" },
  lc: { enName: "Saint Lucia", asset: "lc.svg" },
  mf: { enName: "Saint Martin", asset: "mf.svg" },
  pm: { enName: "Saint Pierre And Miquelon", asset: "pm.svg" },
  vc: { enName: "Saint Vincent And the Grenadines", asset: "vc.svg" },
  ws: { enName: "Samoa", asset: "ws.svg" },
  sm: { enName: "San Marino", asset: "sm.svg" },
  st: { enName: "Sao Tome And Principe", asset: "st.svg" },
  sa: { enName: "Saudi Arabia", asset: "sa.svg" },
  "gb-sct": { enName: "Scotland", asset: "gb-sct.svg" },
  sn: { enName: "Senegal", asset: "sn.svg" },
  rs: { enName: "Serbia", asset: "rs.svg" },
  sc: { enName: "Seychelles", asset: "sc.svg" },
  sl: { enName: "Sierra Leone", asset: "sl.svg" },
  sg: { enName: "Singapore", asset: "sg.svg" },
  sx: { enName: "Sint Maarten", asset: "sx.svg" },
  sk: { enName: "Slovakia", asset: "sk.svg" },
  si: { enName: "Slovenia", asset: "si.svg" },
  sb: { enName: "Solomon Islands", asset: "sb.svg" },
  so: { enName: "Somalia", asset: "so.svg" },
  za: { enName: "South Africa", asset: "za.svg" },
  gs: {
    enName: "South Georgia And the South Sandwich Islands",
    asset: "gs.svg",
  },
  kr: { enName: "South Korea", asset: "kr.svg" },
  ss: { enName: "South Sudan", asset: "ss.svg" },
  es: { enName: "Spain", asset: "es.svg" },
  lk: { enName: "Sri Lanka", asset: "lk.svg" },
  ps: { enName: "State of Palestine", asset: "ps.svg" },
  sd: { enName: "Sudan", asset: "sd.svg" },
  sr: { enName: "Suriname", asset: "sr.svg" },
  sj: { enName: "Svalbard And Jan Mayen", asset: "sj.svg" },
  se: { enName: "Sweden", asset: "se.svg" },
  ch: { enName: "Switzerland", asset: "ch.svg" },
  sy: { enName: "Syria", asset: "sy.svg" },
  tw: { enName: "China Taiwan", asset: "tw.svg" },
  tj: { enName: "Tajikistan", asset: "tj.svg" },
  tz: { enName: "Tanzania", asset: "tz.svg" },
  th: { enName: "Thailand", asset: "th.svg" },
  tl: { enName: "Timor-Leste", asset: "tl.svg" },
  tg: { enName: "Togo", asset: "tg.svg" },
  tk: { enName: "Tokelau", asset: "tk.svg" },
  to: { enName: "Tonga", asset: "to.svg" },
  tt: { enName: "Trinidad And Tobago", asset: "tt.svg" },
  ta: { enName: "Tristan da Cunha", asset: "ta.svg" },
  tn: { enName: "Tunisia", asset: "tn.svg" },
  tr: { enName: "Turkey", asset: "tr.svg" },
  tm: { enName: "Turkmenistan", asset: "tm.svg" },
  tc: { enName: "Turks And Caicos Islands", asset: "tc.svg" },
  tv: { enName: "Tuvalu", asset: "tv.svg" },
  ug: { enName: "Uganda", asset: "ug.svg" },
  ua: { enName: "Ukraine", asset: "ua.svg" },
  ae: { enName: "United Arab Emirates", asset: "ae.svg" },
  gb: { enName: "United Kingdom", asset: "gb.svg" },
  un: { enName: "United Nations", asset: "un.svg" },
  um: { enName: "United States Minor Outlying Islands", asset: "um.svg" },
  us: { enName: "United States of America", asset: "us.svg" },
  xx: { enName: "Unknown", asset: "xx.svg" },
  uy: { enName: "Uruguay", asset: "uy.svg" },
  uz: { enName: "Uzbekistan", asset: "uz.svg" },
  vu: { enName: "Vanuatu", asset: "vu.svg" },
  ve: { enName: "Venezuela", asset: "ve.svg" },
  vn: { enName: "Vietnam", asset: "vn.svg" },
  vg: { enName: "Virgin Islands (British)", asset: "vg.svg" },
  vi: { enName: "Virgin Islands (U.S.)", asset: "vi.svg" },
  "gb-wls": { enName: "Wales", asset: "gb-wls.svg" },
  wf: { enName: "Wallis And Futuna", asset: "wf.svg" },
  eh: { enName: "Western Sahara", asset: "eh.svg" },
  ye: { enName: "Yemen", asset: "ye.svg" },
  zm: { enName: "Zambia", asset: "zm.svg" },
  zw: { enName: "Zimbabwe", asset: "zw.svg" },
};
